**2. Load trained model & make predictions**

In [1]:
# make sure the libraries are installed where these models are getting loaded
%pip install -q numpy pandas scikit-learn joblib

WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/sameersuman/Documents/ML_bootcamp/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

**Load joblib version**

In [2]:
import pandas as pd
from joblib import load

In [3]:

joblib_path = "/Users/sameersuman/Documents/ML_bootcamp/13.ml_model_deployment/1.saving_and_loading_trained_model/model_dir/diabetes_model_pipeline.joblib"

In [4]:
# load the saved model
loaded_joblib_pipeline = load(joblib_path)

In [10]:

# example new patient data
new_data = pd.DataFrame({
    "Pregnancies": [2],
    "Glucose": [120],
    "BloodPressure": [70],
    "SkinThickness": [25],
    "Insulin": [80],
    "BMI": [28.5],
    "DiabetesPedigreeFunction": [0.45],
    "Age": [35]
})

new_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2,120,70,25,80,28.5,0.45,35

In [11]:
# data will be scaled and passed on to the model for prediction inside the pipeline
prediction = loaded_joblib_pipeline.predict(new_data)
print("Predicted class:", prediction[0])

if prediction[0] == 1:
    print("⚠️ Model predicts: Diabetes")
else:
    print("✅ Model predictes: No Diabetes")

Predicted class: 0
✅ Model predictes: No Diabetes

In [16]:
multiple_patients_data = pd.DataFrame({
    "Pregnancies": [2, 0, 5, 1, 8],
    "Glucose": [120, 85, 165, 105, 180],
    "BloodPressure": [70, 60, 85, 65, 90],
    "SkinThickness": [25, 15, 30, 20, 40],
    "Insulin": [80, 50, 120, 60, 200],
    "BMI": [28.5, 22.0, 35.5, 25.0, 42.1],
    "DiabetesPedigreeFunction": [0.45, 0.21, 0.62, 0.35, 1.05],
    "Age": [35, 22, 45, 28, 55]
})
multiple_patients_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2,120,70,25,80,28.5,0.45,35
1,0,85,60,15,50,22.0,0.21,22
2,5,165,85,30,120,35.5,0.62,45
3,1,105,65,20,60,25.0,0.35,28
4,8,180,90,40,200,42.1,1.05,55

In [19]:
# 2. Make predictions for all 5 patients at once
# (Assuming your loaded model is named 'loaded_joblib_pipeline')
predictions = loaded_joblib_pipeline.predict(multiple_patients_data)
print("\n--- Prediction Results ---")
# 3. Loop through the predictions and print them nicely
for index, prediction in enumerate(predictions):
    if prediction == 1:
        result = "⚠️ Model predicts: Diabetes"
    else:
        result = "✅ Model predictes: No Diabeteson"
        
    print(f"Patient {index + 1}: {result}")

--- Prediction Results ---
Patient 1: ✅ Model predictes: No Diabeteson
Patient 2: ✅ Model predictes: No Diabeteson
Patient 3: ⚠️ Model predicts: Diabetes
Patient 4: ✅ Model predictes: No Diabeteson
Patient 5: ⚠️ Model predicts: Diabetes

**Load pickle version**

In [13]:
import pandas as pd
import pickle

# create model_dir
# path where model file need to be saved
pickle_path = "/Users/sameersuman/Documents/ML_bootcamp/13.ml_model_deployment/1.saving_and_loading_trained_model/model_dir/diabetes_model_pipeline_pickle.pkl"
# load the trained pipeline using pickle
with open(pickle_path, "rb") as file:
    loaded_pickle_pipeline = pickle.load(file)

# example new patient data
new_data = pd.DataFrame({
    "Pregnancies": [2],
    "Glucose": [120],
    "BloodPressure": [70],
    "SkinThickness": [25],
    "Insulin": [80],
    "BMI": [28.5],
    "DiabetesPedigreeFunction": [0.45],
    "Age": [35]
})

new_data

# data will be scaled and passed to the model automatically inside the pipeline
prediction = loaded_pickle_pipeline.predict(new_data)
print("Predicted class:", prediction[0])

if prediction[0] == 1:
    print("⚠️ Model predicts: Diabetes")
else:
    print("✅ Model predicts: No Diabetes")

Predicted class: 0
✅ Model predicts: No Diabetes